### ISSUE TITLE
Header - Links have large outlines

### ISSUE THREAD

**Issue by leahdodd** [UDelIT/udthemebrand#30]
** This might be a non-issue. Maybe a choice due to accessibility compliance? 

On desktop:
When I mouse over the links in the header UD lockup, visit/apply/give/site title, I see large outlines. Not sure if this is intentional. It is causing a confusing experience since it is not consistent across our sites. 

On mobile:
Same as above when tapping links. 

<img width="601" alt="header-outlines" src="https://user-images.githubusercontent.com/43443501/45821454-3b04af80-bcb7-11e8-9092-2efdc698543f.png">

**Comment by atsea** [comment]
Confirmed fixed. This is a duplicate created prior to #35
