### ISSUE TITLE
Footer Icons

### ISSUE THREAD

**Issue by leahdodd** [UDelIT/udthemebrand#32]
The footer displays large icons below the footer.  Screenshot submitted. Observed on all desktop browsers on my machine (Mac Chrome Version 68.0.3440.106, Firefox, Safari Version 12.0). This is also happening on mobile (iPhone 6s safari).

<img width="1465" alt="screen shot 2018-09-20 at 9 28 20 am" src="https://user-images.githubusercontent.com/43443501/45821561-88811c80-bcb7-11e8-87eb-f4b8d4755679.png">

**Comment by leahdodd** [comment]
Update: This appears to display even when the footer is disabled. They then appear in white, so they're not easily visible but add lots of extra space to the bottom of each page.

**Comment by atsea** [comment]
Leah, take a look again, this should be fixed.

**Comment by atsea** [comment]
Confirmed fixed.
